FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    software-properties-common \
    apt-transport-https \
    gnupg \
    lsb-release \
    python3 \
    python3-pip

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

RUN apt-get update && apt-get install -y docker-ce

RUN service docker start

RUN docker --version

# RUN curl -fsSL https://get.docker.com -o get-docker.sh

# RUN sh get-docker.sh

# RUN service docker start

COPY . /pyrexiadsim_execute/

WORKDIR /pyrexiadsim_execute
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /pyrexiadsim_execute
ENTRYPOINT ["python3", "container_generator.py"] 
