FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    python3 \
    python3-pip

RUN curl -fsSL https://get.docker.com -o get-docker.sh

RUN sh get-docker.sh

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9

COPY . /pyrexiadsim_execute/

WORKDIR /pyrexiadsim_execute
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /pyrexiadsim_execute
ENTRYPOINT ["python3", "container_generator.py"] 
